repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0-alpha.0
    hooks:
      - id: eslint
        exclude: ""

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/boidolr/pre-commit-images
    rev: v1.5.1
    hooks:
      - id: optimize-jpg
        args: ["--threshold", "0"]
      - id: optimize-png
        args: ["--threshold", "0"]
      - id: optimize-svg
        args: ["--threshold", "0"]
      - id: optimize-webp
        args: ["--threshold", "0"]
  - repo: local
    hooks:
      - id: eleventy-build
        name: eleventy-build
        entry: npx @11ty/eleventy
        language: system
        pass_filenames: false

exclude: (docs/|README.md)
